Repository Dire-Delivery/dire-delivery-frontend, pull requests merged in 2025-03, with the labels that each got.

#22 21 fix sidebar stuff
  app/(routes)/admin/orders/[orderid]/page.tsx
  components/shared/layout/sidebar-layout.tsx
  package-lock.json
  package.json
  tailwind.config.ts
Labels: bug

#25 chore: change admin pages to owner
  app/(routes)/owner/admins/page.tsx
  app/(routes)/owner/employees/page.tsx
  app/(routes)/owner/help/page.tsx
  app/(routes)/owner/orders/[orderid]/page.tsx
  app/(routes)/owner/orders/page.tsx
  app/(routes)/owner/page.tsx
  app/(routes)/owner/settings/page.tsx
  components/order/admin/orderTable.tsx
  components/shared/layout/app-sidebar.tsx
  components/shared/layout/sidebar-layout.tsx
  data/layout.ts
Labels: enhancement

#29 28 setting page for owner
  actions/cities.ts
  actions/price.ts
  app/(routes)/admin/setting/page.tsx
  app/(routes)/owner/settings/page.tsx
  components/order/addOrderDialogue.tsx
  components/ownerComponents/cityColumn.tsx
  components/ownerComponents/cityTable.tsx
  components/ownerComponents/priceCity.tsx
  components/ownerComponents/profile.tsx
  components/ownerComponents/sidebar.tsx
  data/endPoints.ts
  ordersDb.json
  types/cities.ts
  types/price.ts
Labels: enhancement

#31 30 setting page for admin
  app/(routes)/admin/settings/page.tsx
Labels: enhancement

#40 37 impelment middleware auto sign in with remember funcitonality and logout
  actions/auth.ts
  app/(auth)/add-details/page.tsx
  app/(auth)/add-user/page.tsx
  app/(auth)/log-in/page.tsx
  app/(auth)/log-out/page.tsx
  base-api/api.ts
  components/shared/layout/header.tsx
  components/shared/layout/sidebar-layout.tsx
  middleware.ts
  package-lock.json
  package.json
  types/auth.ts
Labels: bug, enhancement

#42 41 change token fetching back into the api url
  actions/auth.ts
  app/(routes)/admin/orders/page.tsx
  base-api/api.ts
  components/order/owner/orderTable.tsx
Labels: bug

#54 15 implement employees page
  actions/auth.ts
  actions/employee.ts
  app/(auth)/add-user/page.tsx
  app/(auth)/auth/reset-password/[forgotPwdToken]/page.tsx
  app/(auth)/log-in/page.tsx
  app/(routes)/admin/employees/page.tsx
  app/(routes)/owner/admins/page.tsx
  app/(routes)/owner/employees/[employeeId]/page.tsx
  app/(routes)/owner/employees/page.tsx
  app/(routes)/owner/orders/[orderid]/page.tsx
  base-api/api.ts
  components/order/owner/addEmployeeDialogue.tsx
  components/order/owner/orderTable.tsx
  components/order/owner/peopleColumn.tsx
  components/order/owner/peopleTable.tsx
  components/shared/layout/base-layout.tsx
  components/shared/layout/header.tsx
  components/shared/layout/sidebar-layout.tsx
  components/shared/personOrderTableView.tsx
  components/views/UserView.tsx
  data/endPoints.ts
  employeesDb.json
  lib/auth-schema.ts
  lib/utils.ts
  middleware.ts
  package-lock.json
  package.json
  public/Icons/black Plane.svg
  public/images/done.svg
  public/images/person.png
  public/images/resetBackground.png
  types/adminType.ts
  types/auth.ts
  types/employeeType.ts
  types/orderStatus.ts
Labels: bug, enhancement

#55 53 implement admin page
  actions/employee.ts
  app/(auth)/add-details/page.tsx
  app/(auth)/log-in/page.tsx
  app/(routes)/admin/employees/[employeeId]/page.tsx
  app/(routes)/admin/employees/[userId]/page.tsx
  app/(routes)/admin/employees/page.tsx
  app/(routes)/owner/admins/[userId]/page.tsx
  app/(routes)/owner/admins/page.tsx
  app/(routes)/owner/employees/[employeeId]/page.tsx
  app/(routes)/owner/employees/[userId]/page.tsx
  app/(routes)/owner/employees/page.tsx
  components/order/owner/addEmployeeDialogue.tsx
  components/order/owner/peopleTable.tsx
  components/shared/userOrderTableView.tsx
  components/views/usersView.tsx
Labels: bug, enhancement

#56 51 reviewing bugs on order integration
  actions/dashboard.ts
  actions/order.ts
  app/(routes)/admin/orders/[orderid]/page.tsx
  app/(routes)/employee/orders/[orderid]/page.tsx
  app/(routes)/owner/orders/[orderid]/page.tsx
  components/dashboard/dashboarview.tsx
  components/order/orderTableView.tsx
  components/order/owner/orderTable.tsx
  components/ownerComponents/priceCity.tsx
  components/trackorder/factories.tsx
  hooks/use-toast.ts
  types/cities.ts
  types/dashboard.ts
Labels: bug, enhancement

#59 58 fix UI bugs
  app/(auth)/add-details/page.tsx
  app/(auth)/auth/reset-password/[forgotPwdToken]/page.tsx
  app/(auth)/log-in/page.tsx
  components/order/owner/addEmployeeDialogue.tsx
  components/order/owner/peopleTable.tsx
  components/shared/layout/header.tsx
  components/shared/layout/sidebar-layout.tsx
Labels: bug
